--ÖDEME TÜRÜNE GÖRE DAÐILIM
SELECT 
DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
CASE 
	WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=1 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS
GROUP BY DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_), PAYMENTTYPE
ORDER BY DATEPART(MONTH,DATE_),DATEPART(YEAR,DATE_)