--Kullanýcý Adý - Ad Soyad - Ýl - Ýlçe - Semt - AçýkAdres - Sipariþ Id - Tarih
--Toplam tutar - Ödeme tarihi - Banka - Onay Kodu - Kargo Fiþ No

SELECT
	U.USERNAME_ AS KULLANICIADI ,
	U.NAMESURNAME AS ADSOYAD,
	CT.CITY AS IL, T.TOWN AS ILCE , D.DISTRICT AS SEMT,
	A.ADDRESSTEXT AS ACIKADRES,
	O.ID AS SIPARISID, O.DATE_ AS TARÝH, O.TOTALPRICE AS TOPLAMTUTAR,
	P.DATE_ AS ODEMETARÝHÝ,P.APPROVECODE AS BANKAONAYKODU,
	I.DATE_ AS FATURATARÝHÝ,I.CARGOFICHENO AS KARGOFÝSNO
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
