SELECT* FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND DISTRICT='BAÞAKÞEHÝR'

SELECT* FROM CUSTOMERS
WHERE GENDER='E' AND DISTRICT='ÜSKÜDAR'

SELECT* FROM CUSTOMERS
WHERE GENDER='E' AND BIRTHDATE BETWEEN '19900101' AND '20000101'

