SELECT ID, CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER
FROM
CUSTOMERS

INSERT INTO CUSTOMERS
( CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER)
VALUES
('MEHMET TEKÝN','ANTALYA','1990-06-04','ALANYA','E')