INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('VOLKAN TETKÝ','BARTIN','1997-03-07','KURUCAÞÝLE','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('SEMÝH AKTEPE','ÝSTANBUL','1985-07-07','BAÞAKÞEHÝR','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('VEYSEL DEMÝR','ÝZMÝR','1990-03-07','GÖZTEPE','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('UMUT YÝTÝK','ANKARA','1994-01-07','KIZILCAHAMAM','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('BANU TARKAN','KIRIKKALE','1996-05-07','KESKÝN','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('GÖZDE DEÐÝL','ESKÝÞEHÝR','1986-10-07','ODUNPAZARI','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('DÖNDÜ TEKER','MANÝSA','1984-11-07','KIRKAÐAÇ','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('DURMUÞ ARABA','ANKARA','1988-06-07','MAMAK','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('SELMA GÖRMEZ','ÝSTANBUL','1999-04-07','ÜSKÜDAR','E','TR',25)

INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('TAHSÝN PEKMEZ','KOCAELÝ','1997-05-07','GEBZE','E','TR',25)

SELECT* FROM CUSTOMERS

