INSERT INTO CUSTOMERS(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER, NATION, AGE) 
VALUES ('VOLKAN TETKÝ','BARTIN','1997-03-07','KURUCAÞÝLE','E','TR',25)

SELECT* FROM CUSTOMERS

TRUNCATE TABLE CUSTOMERS