
--ÝSMÝ BANU TARKAN OLAN
SELECT* FROM CUSTOMERS

WHERE CUSTOMERNAME='BANU TARKAN'


--ÞEHRÝ ÝSTANBUL OLANLAR
SELECT* FROM CUSTOMERS

WHERE CITY='ÝSTANBUL'


--EÞÝT DEÐÝLDÝR
SELECT* FROM CUSTOMERS

WHERE CITY<>'ÝZMÝR' 


--1997 DEN SONRA DOÐANLAR
SELECT* FROM CUSTOMERS

WHERE BIRTHDATE>'1997-01-01'

--97 DEN ÖNCE DOÐANLAR
SELECT* FROM CUSTOMERS

WHERE BIRTHDATE<'1997-01-01'

--2 TARÝH ARASI KAYITLAR
SELECT* FROM CUSTOMERS

WHERE BIRTHDATE BETWEEN'1990-01-01' AND '1997-01-01'


-- AGE ALANINI GÜNCELLÝYORUM
UPDATE CUSTOMERS SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())


--22 ÝLE 30 YAÞ ARASINDAKÝLERÝ LÝSTELER	
SELECT* FROM CUSTOMERS

WHERE AGE BETWEEN 22 AND 30


--BANU ÝLE BAÞLAYAN KAYITLAR
SELECT* FROM CUSTOMERS

WHERE CUSTOMERNAME LIKE 'BANU%'

-- SONU AKTEPE BÝTENLER
SELECT* FROM CUSTOMERS

WHERE CUSTOMERNAME LIKE '%AKTEPE'

--SONU AKTEPE ÝLE BÝTMEYENLER
SELECT* FROM CUSTOMERS

WHERE CUSTOMERNAME NOT LIKE '%AKTEPE'

--ÝSTANBUL VE ANKARADA BULUNANLAR
SELECT* FROM CUSTOMERS

WHERE CITY IN ('ÝSTANBUL','ANKARA')

UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'





