SELECT
U.NAMESURNAME AS ADSOYAD,
U.EMAIL MAILADRESI,
U.GENDER CINSIYET,
U.BIRTHDATE DOGUMTARIHI,
C.COUNTRY AS ULKE, CT.CITY AS SEHIR,
T.TOWN AS ILCE, D.DISTRICT AS ILCE,
A.POSTALCODE AS POSTAKODU,
A.ADDRESSTEXT AS ACIKADRES
FROM
USERS U, ADDRESS A, COUNTRIES C, CITIES CT,
TOWNS T, DISTRICTS D

WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
--AND U.ID=4
AND CT.CITY LIKE 'BURSA'
ORDER BY U.NAMESURNAME
